### ISSUE TITLE
Error creating WebGL context. 

### ISSUE THREAD

**Issue by heaversm** [spite/GSVPano.js#2]
Hey - I've downloaded and tried to run locally your examples, and I get an "Error creating WebGL context." The same thing happens in your online example. I'm using Chrome Canary on Mac 10.7.5 - is there an error with the code or maybe something in my system? I feel like I saw this example working at some point recently.

**Comment by spite** [comment]
Sounds like a more general WebGL problem. You should try other WebGL demos, or going to http://get.webgl.org/ and see if it's supported. Your graphics card might be blacklisted in the last update of Canary. If that were the case, you might try removing the blacklisting from chrome with the option "Override software rendering list".

**Comment by heaversm** [comment]
Think you're right actually. Strange...I think its a graphics card issue
actually.

On Mon, Aug 5, 2013 at 5:17 AM, Jaume Sanchez notifications@github.comwrote:

> Sounds like a more general WebGL problem. You should try other WebGL
> demos, or going to http://get.webgl.org/ and see if it's supported. Your
> graphics card might be blacklisted in the last update of Canary. If that
> were the case, you might try removing the blacklisting from chrome with the
> option "Override software rendering list".
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/spite/GSVPano.js/issues/2#issuecomment-22095005
> .

## 

Mike Heavers
mikeheavers.com
917-345-6634

**Comment by spite** [comment]
Ok then. You can use the "override software rendering list", or file a bug in the chromium project. Ta.
