### ISSUE TITLE
Flipped panoramas

### ISSUE THREAD

**Issue by dineshj1** [spite/GSVPano.js#4]
Great tool! 

I've been trying to figure this out: why are the returned panoramas sometimes flipped?

**Comment by spite** [comment]
Can you provide an example of a flipped panorama? the lat lng or the address will suffice

**Comment by dineshj1** [comment]
I was just about to update my comment with this:

Example: This happened for LatLng(48.863242, 2.367167) in the example.html code. You can see the panoramas are flipped by looking at the Google watermarks, but also from actually going to the location on streetview: https://www.google.com/maps/place/48%C2%B051'47.7%22N+2%C2%B022'01.8%22E/@48.863242,2.367167,3a,90y,178.61h,72.78t/data=!3m4!1e1!3m2!1sj0pWB8MHzLcvryCkQkOx4Q!2e0!4m2!3m1!1s0x0:0x0!6m1!1e1

**Comment by spite** [comment]
I think that version you have downloads all panoramas flipped. I think it was so I could map them into a inside-out flipped sphere mesh.

Try this version of the library, it's quite more recent: http://www.clicktorelease.com/code/world-cup-2014/js/GSVPano.js

_Note_: it works exactly the same, but returns an array of canvases if the final canvas hits the texture size limit. For all intents and purposes, you should be ok with using your old code replacing the use of <code>this.canvas</code> in <code>onPanoramaLoad</code> to <code>this.canvas[ 0 ]</code>

**Comment by dineshj1** [comment]
Ah, my bad, sorry and thanks for the quick responses. (I was using a version of the library that I'd downloaded earlier with GSVPanoDepth.js)
